### ISSUE TITLE
Images are previewed although data saving is enabled

### ISSUE THREAD

**Issue by Faldrian** [vanita5/twittnuker#100]
I have the Option "save bandwidth" enabled and was hoping twittnuker would only load previews inside the timeline when WLAN is active. Turns out, it loads those previews even when only mobile data is available.
I use the version currently distributed in the play store, it updated today.

![screenshot_20160419-181657](https://cloud.githubusercontent.com/assets/1184859/14646803/3d9463f4-065b-11e6-9375-50646d4b9aa5.png)
![screenshot_20160419-181649](https://cloud.githubusercontent.com/assets/1184859/14646804/3d948406-065b-11e6-9a1d-32ba750786b6.png)

**Comment by vanita5** [comment]
thanks, should be fixed!
