### ISSUE TITLE
why is streaming greyed out?

### ISSUE THREAD

**Issue by 0x1f415** [vanita5/twittnuker#102]
apologies if this has already been answered but I couldn't find it anywhere.

latest CM13 nightly, latest play store build, tried both default and twitter for android's api keys

![tmp_17590-screenshot_20160430-135249-125652127](https://cloud.githubusercontent.com/assets/6064300/14937626/67016876-0edb-11e6-85e2-8c0219729a2c.png)

**Comment by 0x1f415** [comment]
just re-installed (from f-droid this time) and noticed it shows a toast "straming is broken, disabling". no information as to why this is, though...

**Comment by 0x1f415** [comment]
oh, I see now: https://github.com/vanita5/twittnuker/blame/b6a835e3fd26491e5d4ec8052a63d134c43b96c6/twittnuker/src/main/java/de/vanita5/twittnuker/service/StreamingService.java#L210-L218

**Comment by vanita5** [comment]
Force close.

Streaming is totally broken atm.

**Comment by Garry050** [comment]
look Twitter API status....
https://dev.twitter.com/overview/status
It seems to have suddenly changed the version of the API... 
From 2.0 it seems to have been changed to 1.1.
(f**king twitter developer.......)

sorry my bad english

Source http://blog.livedoor.jp/blackwingcat/archives/1928136.html (Japanese)

**Comment by vanita5** [comment]
Twittnuker uses 1.1 endpoint for streaming. That's not the problem at the moment.

But thanks for pointing this out!

**Comment by Garry050** [comment]
TwittNuker 0.9.0 released. but not fix userstream..
Cannot fix bug...?

**Comment by vanita5** [comment]
I'm not quite sure what actually causes the problem and I didn't have the time to look further into it.

**Comment by vanita5** [comment]
Streaming is back, see latest versions.
