### ISSUE TITLE
Volume of GIFs 

### ISSUE THREAD

**Issue by Clouddancer** [vanita5/twittnuker#103]
The volume in GIFs can't be put on loud any longer.

**Comment by sandzwerg** [comment]
You have to stop the gif, then you can enable/disable the volume again. Not sure why you'll need to do it this way know though. I would prefer it, if it would be possible to change the setting while the gif is playing like it was before.

**Comment by Clouddancer** [comment]
Thank you. It works the way you explained it.

**Comment by vanita5** [comment]
GIFs don't have sound, you're talking about videos.

This issue has been fixed.
