### ISSUE TITLE
GIFs muted until end of playback

### ISSUE THREAD

**Issue by alerque** [vanita5/twittnuker#105]
I'm having a hard time with media items attached to tweets. On regular frustration is that GIFs start as muted (probably a good thing) but I am unable to unmute them until they reach the end of playback. At that point the unmute works and I can restart playback at the beginning and watch with sound.

As if GIFs weren't generally a waste of time anyway, now even the ones I do open take 2× the time to view :(

**Comment by okoetter** [comment]
How do you unmute them? If I tap on the crossed out microphone symbol nothing happens.

**Comment by mkody** [comment]
Wait-- GIFs don't have sound. Did you mean videos?

**Comment by alerque** [comment]
It's not apparent in Twitnuker what the media type is for any given attachment, but yes obviously these would be something other that plain GIFs.

**Comment by vanita5** [comment]
Fixed in latest commits. Thanks!

**Comment by alerque** [comment]
Awesome! Will be looking for it in the next Play store release.
