### ISSUE TITLE
GIF sound steals but does not return sound

### ISSUE THREAD

**Issue by alerque** [vanita5/twittnuker#106]
Sound playback from embeded media steels my phones sound playback focus — so music or podcasts pause when I play some media it Twittnuker — but focus is never returned so it does not resume. I have to manually switch apps to restart playback.

Media playback from Twittnuker should be marked as some sort of temporary interruption so that other audio apps know to go back to what they were playing.v

**Comment by vanita5** [comment]
Is this issue still present in the latest version?

**Comment by alerque** [comment]
No actually I noticed just the other day it returned playback control so I think this has been resolved. Thanks.
