### ISSUE TITLE
Twitter/Twitter for Android API Problem

### ISSUE THREAD

**Issue by Clouddancer** [vanita5/twittnuker#107]
When I use the "Twitter for Android" api, the "interactions" timeline doesn't update. I can send pictures via DM using this API.

When I change to the "Twitter" API, the "Interactions" timeline updates but when I try to send a picture via DM, it shows the error message "Error 37. Not autorized to use this endpoint."

**Comment by vanita5** [comment]
Never had a problem with the interactions tab.

Please reopen if the bug is still present!

**Comment by Clouddancer** [comment]
I have this problem again except this time no button for uploading a picture in a DM while using the “Twitter“ api.
