### ISSUE TITLE
Character limit change overflows tweets

### ISSUE THREAD

**Issue by alerque** [vanita5/twittnuker#108]
Twitter's new character count limits are causing a lot of tweets to show up in the timeline truncated with a link to read the rest. This makes for a poor reading experience. There must be an updated way to request full tweets from the API.

**Comment by vanita5** [comment]
This has already been implemented. I'll publish an update soon!

**Comment by alerque** [comment]
What ever happened to this? You may have it on your device but just a reminder those of running the play store release have unreadable feeds where a large percentage of tweets are trunc

**Comment by vanita5** [comment]
That's not quite true. I released Twittnuker 0.9.0 over a week ago, so the current Play Store version contains the new character count implementation.

**Comment by alerque** [comment]
Huh. The Play store is still showing me 0.8.3.

**Comment by vanita5** [comment]
oh well 😄
