### ISSUE TITLE
Latest nightly build (Oct 24, 2016) crashes on start

### ISSUE THREAD

**Issue by gena01** [vanita5/twittnuker#113]
After a clean install the Twittnuker crashes on startup. This one is a bit strange since this is right after install and before adding twitter login or doing any other interactions.

**Comment by vanita5** [comment]
After the CI build has finished (https://travis-ci.org/vanita5/twittnuker/builds/171160554), download the new version and try again.

Looks like ProGuard removed some classes or functions from the theming library.

**Comment by okoetter** [comment]
Sorry to ask here but where do I find nightly builds? Cannot seem to find it on the above Travis site...
