### ISSUE TITLE
Can not sign in with latest nightly

### ISSUE THREAD

**Issue by gena01** [vanita5/twittnuker#117]
Seems like with latest nightly i can't sign in. I keep getting tooltip saying: "error signing in" instead of opening a browser window and a "please wait" spinner.

**Comment by vanita5** [comment]
Did you try the latest one from a few minutes ago? This should already be fixed.

**Comment by gena01** [comment]
Just tried it again. Used different browser to download, same issue. :(

**Comment by vanita5** [comment]
Nightlies are missing the default API keys. Try going to presets in the API settings and Choose Twitter for Android. Official keys are much better anyway ;)

Will be fixed in the next few days.
