### ISSUE TITLE
Twitter/Twitter for Android Api Problem again

### ISSUE THREAD

**Issue by Clouddancer** [vanita5/twittnuker#118]
It's the same problem https://github.com/vanita5/twittnuker/issues/107 except this time no button for uploading a picture in a DM while using the “Twitter“ api.

**Comment by vanita5** [comment]
Which version are you using?

**Comment by Clouddancer** [comment]
Version 0.9.0-2, the recent one.

**Comment by vanita5** [comment]
Should be fixed. Please reopen, if issue still perists.
