### ISSUE TITLE
Question/Request "Who liked my stuff" possible?

### ISSUE THREAD

**Issue by Nedorus** [vanita5/twittnuker#119]
Is there a way to set up a tab whoch will show who like/faved/retweeted my tweets. This would be in analogy to the appropriate “bell“tab in the official Twitter App.

I this isn't possible currently I would like to reqiest this.

P.S.: I signed up just now to add to the twittnuker project. So if I don't know all the rules and howtos pf GITHUB fell free to let me know...

**Comment by vanita5** [comment]
Hey,

first of all, thank you and welcome to GitHub! 😄 

The problem with showing events like retweets, favs, followings etc. is, that Twitter oficially has not made this available for third-party clients like Twittnuker.

The good news is, that you can circumvent this restriction by using official API keys from the Twitter for Android app for example. And Twittnuker has custom API settings to allow the use of custom API keys.

So, to enable events in the interaction tab, simply remove your account from Twittnuker, open the API settings, paste in official API keys if you can find them (or look into the presets 🙈), and relogin.

**Comment by Nedorus** [comment]
Thanks for this! Works like a charm! However, it serms I also needed to change the preset url to
https://[DOMAIN].twitter.com/
it is by default .] insyead of ].

**Comment by Nedorus** [comment]
Thanks for this! Works like a charm! However, it serms I also needed to change the preset url to
https://[DOMAIN].twitter.com/
it is by default .] instead of ].

**Comment by vanita5** [comment]
Actually, https://[DOMAIN **.]** twitter.com/ should be the correct url, however in case of Twitter, it should work either way.
