### ISSUE TITLE
Bug: Fav button (heart) not showing correct status

### ISSUE THREAD

**Issue by Nedorus** [vanita5/twittnuker#120]
When liking / favouriting tweets sometimes the fav button will not correctly turn red. When clicking again, I will receive the error message that  I have already faved/liked this tweet. Checking on the official app it shows correct status, so the fav/like was successfull. 
As a first workaround it would be great if the status would be updated correctly after receiving the error message. 
Always setting the status correctly would of course also be nice.

Btw this also happens with the retweet button.

**Comment by vanita5** [comment]
Thanks, I'll look into this.

**Comment by Nedorus** [comment]
Additional info: I checked Twidere again and it shows the exact same behaviour. Maybe this helps in locating the root cause.

**Comment by vanita5** [comment]
Should be fixed
