### ISSUE TITLE
Feature Request: Button to bring up the left menu

### ISSUE THREAD

**Issue by sternenseemann** [vanita5/twittnuker#125]
There is a pretty simple reason for that: I use Twittnuker on Sailfish OS which uses the same gesture to go back to the home screen. I can still bring it up, but I need at least ten tries or so.

One possibility woud be to use the android (hardware) menu button, which is usable on Sailfish OS android emulation.

**Comment by vanita5** [comment]
Check "Other Settings" -> Menu Button

**Comment by sternenseemann** [comment]
Thank you.
