### ISSUE TITLE
Wrong exclude_reply_user_ids parameter caused wrong reply mentions

### ISSUE THREAD

**Issue by mariotaku** [vanita5/twittnuker#126]
You should notice that in https://github.com/TwidereProject/Twidere-Android/commit/94560df05ff5a3d58e1e80d8c9951f2f2b1522c4 .

Twitter gives us wrong parameter name in their document, which should be **`exclude_reply_user_ids`** rather than **`exclude_reply_userids`**, see [this thread](https://twittercommunity.com/t/exclude-reply-userids-is-being-ignored/84689)

**Comment by vanita5** [comment]
Interesting, thanks for pointing this out.
