### ISSUE TITLE
"Load more" button in notifications tab

### ISSUE THREAD

**Issue by Nervulox** [vanita5/twittnuker#131]
Sometimes the "Load more" button appears in the notificacions tab INSTEAD of the last notification, not under it or something, it just replaces the last notification (Didnt noticed if only on mentions, but could be).

Btw as a request, would be nice an option to disable the "Load more" button at all, I dont know if its in the API or if you could do something.

Using the last version, Android 5.1, Streming enabled and Wi-Fi.

**Comment by vanita5** [comment]
Duplicate #130
