### ISSUE TITLE
App crashed on start

### ISSUE THREAD

**Issue by Dtrieb** [vanita5/twittnuker#132]
After the new update twittnuker crashed directly.

**Comment by Clouddancer** [comment]
I have the same problem after the update.

**Comment by vanita5** [comment]
Seems to be fixed. Thanks for reporting!

**Comment by alerque** [comment]
Same here. Is there a point release coming out to address this? I can't open it at all and don't see a pending update yet.

**Comment by vanita5** [comment]
Version 2.0.1 fixes this crash. It's already in the Play Store and on twittnuker.org

**Comment by alerque** [comment]
Alright thanks. I live in a country that is low priority for rollouts and it routinely takes a couple days to get Play store updates so good to at least know it's coming.
