### ISSUE TITLE
Bugged Favorite-Tab and Drafts

### ISSUE THREAD

**Issue by nathan-thenut** [vanita5/twittnuker#27]
The favorite tab is not syncing properly e.g tweets unfavorited by my pc client are still being shown there and can't be deleted - an error pops up: "This tweet or page does not exist". Also deleting/sending drafts is not working!

**Comment by nathan-thenut** [comment]
The Delete & Send buttons below the drafts don't work but tapping on a draft and then choosing send or delte in the upper right corner of the screen works...

**Comment by vanita5** [comment]
this has been fixed a while ago
