### ISSUE TITLE
When a hotot.in text is loaded  in a conversation it gets displayed wrong

### ISSUE THREAD

**Issue by remhume** [vanita5/twittnuker#29]
When you open a tweet in Twittnuker and click on a hotot.in link that is somewhere in the conversation (not the actual opened tweet!) the opened tweet gets replaced with the full hotot.in text while it should replace the text of the tweet in the conversation which contained the link.

**Comment by vanita5** [comment]
hotot.in support has been removed lately.
needs to be reimplemented.

**Comment by remhume** [comment]
heh, hotot.in is sadly down, …somebody… didn't care to extend the domain ownership and now it's too late :I
