### ISSUE TITLE
Sometimes images don't get loaded in the compose dialog

### ISSUE THREAD

**Issue by remhume** [vanita5/twittnuker#31]
I don't know the pattern behind it but sometimes, when you specify an image, the image button gets blue and all, but you can't see the image in the background of the compose dialog and when you send the tweet the image isn't included. after restarting the app it usually works.

**Comment by vanita5** [comment]
Never happened to me before. Can you find out on how to reproduce this bug?

**Comment by remhume** [comment]
Didn't happen to me again either, maybe it was just a one-time thing…
