### ISSUE TITLE
Open a tweet's media inside a ViewPager

### ISSUE THREAD

**Issue by R4md4c** [vanita5/twittnuker#34]
When there is a tweet that contains multiple medias(images to be precise), and I click on one of them Twittnuker opens only the one I clicked into a new activity( or fragment), It would be great if that activity was a ViewPager and I could navigate through the other images of the tweet in that opened activity.

I could write a pull request, but I'm not sure if I should submit that to TwittNuker or Twidere.

**Comment by vanita5** [comment]
this has just been added in the latest commit in Twidere.

But thank you either way! :)

**Comment by R4md4c** [comment]
Oh ! then great, thanks for pointing out
