### ISSUE TITLE
Hide same RT from followers

### ISSUE THREAD

**Issue by risturiz** [vanita5/twittnuker#36]
Hi, it´s posible to hide the same RT from different ppl you follow?

Thanks.

**Comment by vanita5** [comment]
I'm afraid it's not. Twitter sends those tweets via the streaming API.
Filtering out those "duplicate" retweets is possible but in my opionion not worth the effort (aside from how this would decrease the performance).
If you definietly don't want to have duplicate retweets, disable streaming and refresh manually.
