### ISSUE TITLE
Account view needs additional space between user's name and "Standard"

### ISSUE THREAD

**Issue by schwindp** [vanita5/twittnuker#38]
Twittnuker 0.6.0
Android 4.4.2
Samsung GT-I9195

As seen in the attached picture, the account view needs an additional bit of space between the user's name and "Standard".

![account-view](https://cloud.githubusercontent.com/assets/187595/6125142/59bb3696-b113-11e4-9576-74eea59f175f.png)

**Comment by vanita5** [comment]
There are no more "default" accounts
