### ISSUE TITLE
Big hole in timeline (9 hours). How to post-load?

### ISSUE THREAD

**Issue by mhellwig** [vanita5/twittnuker#39]
scenario: phone is on, internet connectivity gets turned off. gets turned on again a few hours later.

what I'm seeing: my timeline is full untill 23:30 yesterday and then the next tweet I see is from 09:15 today, continuing normally from then onward.

a) this should not happen (i.e. after being started again with internet present, the app should load _all_ tweets since being last connected (maybe with a configurable upper limit of tweets, say 100/500/1000 or whatever)
b) even more annoyingly, once it has happened (i.e. now) there seems to be no way for me to trigger the app to get the missing tweets while also keeping my timeline position intact. My only choice seems to be to use e.g. the web client to read the tweets from last night and manually scroll backwards untill I find the point where I have to start reading.

**Comment by mhellwig** [comment]
further note: sometimes, I would see the "load more tweets" button somewhere in my timeline. 

This situation right here would seem an ideal case for this button, only it isn't being displayed.

**Comment by vanita5** [comment]
If you enable autorefresh on streaming in the settings, the app automatically loads the tweets whenever the stream gets started or reconnects. it does however only load up to 200 tweets (this is limited by Twitter, default is 100 tweets which can be configured in the settings), but appends the "load more tweets" button, so you should be able to read your whole timeline.

**Comment by mhellwig** [comment]
I have autorefresh on streaming turned on, but the "load more tweets" button isn't being shown in the 9 hour gap. there's just one tweet from 23:30 and the next from 09:01

**Comment by mhellwig** [comment]
![screenshot_2015-02-12-11-06-46 1](https://cloud.githubusercontent.com/assets/414112/6165469/84c59af2-b2a8-11e4-9ea3-a9c97ac8062d.png)
this is what it looks like

**Comment by vanita5** [comment]
Okay, when you say the internet connection got turned off, how did you do that? And is the autorefresh working generally?

**Comment by mhellwig** [comment]
in general, yes, autorefresh is not a problem.
turning off the internet connection was accomplished by turning off wifi and mobile networking via the normal android system settings.

**Comment by mhellwig** [comment]
Just as an update, this has happened again at least twice.

Occurence #1: I turn off my phone (completely, i.e. poweroff). I turn it on again 3 hours later. Result: a 3-hour-long gap in my timeline and no "load more tweets" button.

Occurence #2: a connectivity issue (i.e. a connection was present but no bits could be transported across it) of 2 hours length. Result: a 2 hour gap in my timeline with no "load more tweets" button being displayed.

So whatever heuristic you are using to determine when to insert this button seems broken. I had to use the official twitter app a few times now to read those gaps and now I am wary whether there might be micro-gaps of a few tweets that get dropped that might not be readily apparent.

**Comment by vanita5** [comment]
Alright, I'll try to fix/improve this.
Don't worry about microgaps though, as long as the internet connection is stable this should not happen.

**Comment by mhellwig** [comment]
Hello back ..

So I've switched to not using streaming mode any more and instead manually pull to update, which has reduced this problem to almost zero. But only almost..

So you've posted a link to a debug build of an updated version to some other issue here and I've been using that for a few days now, liking it a lot. BUT.

E.g. today, I was kinda busy at work. So I've pulled-to-update when I got up in the morning and then next sometime at night when the children were asleep. This got me a timeline back to around 6 p.m. and a "load more" button. Tapping that got me to 4 p.m. or so and a button again. Repeat a few more times and I get to around 1 p.m. and no "load more" button any more, the tweet before the one at 1 p.m. is from 6:45 a.m. or thereabouts. So, a big hole again.

**Comment by mhellwig** [comment]
As a further note, I think this is actually the same as issue #50. When seeing behaviour as described in my last comment and I then cause twittnuker to lose its state (by sliding out my hardware keyboard), I get to the top of my timeline. Scrolling downwards again will, after a few "pull upwards to load older tweets"-actions get me to the same tweet that was the last in my earlier comment and I then can't get any farther than that. I.e. same behaviour as described in issue 50.

**Comment by vanita5** [comment]
should be fixed
