### ISSUE TITLE
Triggering the actions in the '...' menu have no effect in git master

### ISSUE THREAD

**Issue by MoSal** [vanita5/twittnuker#43]
Twittnuker built from source (commit: 254987b104528b9d8568c5d8d54f084a80b8510f).

In the timeline (Home tab), triggering  the actions in the '...' menu (Reply, Quote, Retweet, ..., Add to filter) have no effect.

Using the icons (Reply, Retweet, Favorite) works as intended.

**Comment by vanita5** [comment]
Note: this is a work in progress build, I am aware that some things are not working yet

**Comment by vanita5** [comment]
fixed in c960ecb509cfb06b636e6ca45f62b4e688c1587c
