### ISSUE TITLE
"Load More" should put the oldest tweet where you're looking

### ISSUE THREAD

**Issue by IBBoard** [vanita5/twittnuker#48]
If I have a "Load More" button in the middle of my feed, because I've had a gap, and I click it then TwittNuker currently loads everything in the gap, *but* it leaves me looking at the latest of the new posts. That means that I need to keep scrolling down until I find the tweets that I'd just been reading as I read up my timeline (forward in time, chronologically). It'd be more useful if TwittNuker could put the oldest tweet where I'm looking, and push all of the newer tweets above it.

As a quick ASCII example.

Before:

    |       …      |
    +--------------+
    |   Tweet 20   |
    +--------------+
    |  Load More   |
    +--------------+
    |  Tweet 200   |
    +--------------+
    |       …      |

After press:

    |       …      |
    +--------------+
    |   Tweet 20   |
    +--------------+
    |   Tweet 21   |
    +--------------+
    |   Tweet 22   |
    +--------------+
    |       …      |

What would be more useful:

    |       …      |
    +--------------+
    |   Tweet 198  |
    +--------------+
    |  Tweet 199   |
    +--------------+
    |  Tweet 200   |
    +--------------+
    |       …      |

Relevant settings (that I know of):
 * Remember Position: Yes
 * Load more from top: No
 * Enable streaming: No
 * Auto-refresh: Yes (Home, Mentions and Messages)
 * Refresh interval: 15 mins
 * Refresh in home timeline: Mentions and Inbox
 * Refresh after tweet sent: Yes

**Comment by vanita5** [comment]
Try enabling "Load more from top", this is exactly what you need :)

If you use the latest debug build, this option is now called "Read from bottom", which explains this option a bit better.

**Comment by IBBoard** [comment]
Sorry, I completely misread that option. I thought that was an "I'm an oddball who wants their newest tweets at the bottom, so that I have to keep scrolling down, rather than having new content at the top"!

(For reference, it is under "Content" settings)

**Comment by vanita5** [comment]
Alright!
