### ISSUE TITLE
Auto-refresh/position tracking sometimes removes tweets I'm reading

### ISSUE THREAD

**Issue by IBBoard** [vanita5/twittnuker#49]
This is related to issue #48, but is probably slightly separate.

I don't check Twitter during the day, which means that I've got a ~18 hour gap from about 11pm one day until 5pm the next day when I don't refresh TwittNuker. That's normally fine, and "Load More" appears in the middle of my stream. Clicking it loads more, but by the time I've seen Load More then I've normally "read" the tweet above as well (i.e. I scrolled far enough for it to appear, which reduces the unread count). Sometimes, while I'm still reading tweets, I'll suddenly loose the oldest of the tweets and I'll have to try and re-load old tweets to see the ones that were removed. It doesn't always happen, so I think it is related to read position and the fact that I scrolled slightly too far when I saw the Load More.

Ideally, refresh should keep all tweets up to the tweets that are currently on your screen when it refreshes, rather than just up to its "Last N tweets" caching threshold (or the unread ones, whichever is the larger list).

Relevant settings (that I know of):
 * Remember Position: Yes
 * Load more from top: No
 * Enable streaming: No
 * Auto-refresh: Yes (Home, Mentions and Messages)
 * Refresh interval: 15 mins
 * Refresh in home timeline: Mentions and Inbox
 * Refresh after tweet sent: Yes

**Comment by vanita5** [comment]
Thanks for your feedback!

Read position has been reimplemented. You can try the latest build from here: http://twittnuker.org/download/twittnuker-debug.apk

I'll close this issue for now. Please re-open if the issue still exists in the latest debug version.
