### ISSUE TITLE
Scroll-back to load older tweets often fails

### ISSUE THREAD

**Issue by IBBoard** [vanita5/twittnuker#50]
If I've lost old tweets from my timeline because Twittnuker decided I've read them (see #49) then I'd normally be at the bottom of my timeline. From the bottom of my timeline then I can pull the list up to try to load older tweets (the same as how I can pull it down at the top to load newer tweets). 

Occasionally, this will work. Most of the time, though, I end up with the blue progress bar across the top for a minute or two and then no new tweets. I've not hit any Twitter limits that I'm aware of (because new tweets can be requested at the top) and I don't get any visible errors. Twittnuker just seems to take a long time and then decide it doesn't need to show me anything.

![screenshot_2015-04-30-19-14-11](https://cloud.githubusercontent.com/assets/388582/7419524/834fd938-ef6d-11e4-8e60-93e9eee437e3.png)

**Comment by klonamy** [comment]
If i read this,  i think this bug and https://github.com/vanita5/twittnuker/issues/66 are related?

**Comment by IBBoard** [comment]
I don't think it is related. I was on wifi and my issue was that the loading of old tweets wasn't working and just showed the progress bar for a few minutes before doing nothing, while the other ticket appears to be timeout happening too quick on some connection types.

I *think* I can close this now, though, because I've not had it happen for a while. I've had other loading/scrolling oddities, but not this (as far as I can remember).
