### ISSUE TITLE
Error 261 when trying to (re)tweet or fav

### ISSUE THREAD

**Issue by mhellwig** [vanita5/twittnuker#52]
Since some time yesterday I can't perform any write operations any more. Reading works fine but tweeting, retweeting or favourite-ing is met with "error 261"

**Comment by kunev** [comment]
Looks like twitter decided to cut off the permission :(. I'm not sure there's anything to do, but ask them for the reason and hope they'll give a reasonable explanation and a way to fix things.

**Comment by nathan-thenut** [comment]
And seems like only the dev can ask twitter for the reasons. Since they are going to verify that you're the dev via the dev ID etc.

**Comment by vanita5** [comment]
By now I haven't got a reasonable explanation, still waiting for a reply from Twitter.

Twitter removed write permissions for Twittnuker and several other small Twitter clients including Yuugatter, Tweecha, feather, OpenTween,...

For now you can create your own consumer key/secret on http://apps.twitter.com

**Comment by mhellwig** [comment]
Today things seem to work again, so let's hope it stays that way I guess...
