### ISSUE TITLE
Jump to first position

### ISSUE THREAD

**Issue by unicorn622** [vanita5/twittnuker#55]
I just wanted to ask, if it is possible to add a feature, which  lets you jump to the first position of the actual tab. 
Example: I read something at 13:00 o'clock, at midnight i need that information again; scroll, scroll, scroll to time position 13:00, copy the needed information and scroll all the timeline back again.
This is not that important, just something to make twittnuking easier.

**Comment by vanita5** [comment]
You can just tap on the current tab and it will jump to the top.
