### ISSUE TITLE
Retweets shown even when  disabled

### ISSUE THREAD

**Issue by alerque** [vanita5/twittnuker#59]
I follow a number of people that I want to hear from if they say something directly but that frequently abuse the retweet function and I don't want to see these storms. I have gone into the Twitter site and disabled retweets from these folks. My previous twitter client (the excellent but now atrophying Tweet Lanes) suchessfully showed my my timeline minus these retweets so I know it's possible to do from the API. Somehow.

For some reason Twittnuker is showing me everything, even retweets from these closed accounts and users that I have completely muted. This should be fixed so that it respects my settings.

**Comment by vanita5** [comment]
Should be fixed and enabling/disabling retweets for users has been implemented
