### ISSUE TITLE
Feature request: invert timeline direction

### ISSUE THREAD

**Issue by alerque** [vanita5/twittnuker#60]
I would like to be able to read my timeline from top to bottom. This is easier on the eyes when speed reading. The catch is that I'd like it to remain in chronological order. Currently the app can be tweaked to make it easier to load new content when reading in that direction but this doesn't actually flip the UI direction.

I would like to keep the normal UI paradigm with new items being streamed to the timeline and refreshed from the end, but with the time axis reversed so this always happens at the bottom of the list. Opening a previously unopened tab (with no saved position in the list) should default to the bottom of the frame.

**Comment by vanita5** [comment]
I don't think I'm gonna do this.
There's not enough demand compared to the work that would need to be done.
