### ISSUE TITLE
[0.7.2] TN doesn't stay put when refreshing timeline

### ISSUE THREAD

**Issue by schwindp** [vanita5/twittnuker#65]
When refreshing the timeline (pulling down) TN doesn't stay put at the last read (or seen) Tweet but moves to latest. This seems to be gotten (re)introduced with latest update.

**Comment by vanita5** [comment]
There's an option under Content called "Read from bottom". The update might have overridden the previously set value, as this option has been reimplemented.

Try to enable this option. Twittnuker will behave as it used to!

**Comment by schwindp** [comment]
D'uh. Thanks!
