### ISSUE TITLE
[Q&A] Network error on GPRS

### ISSUE THREAD

**Issue by klonamy** [vanita5/twittnuker#66]
After the last 3 or 4 Updates (Matherial Design) the timeout on slow internet connections, e. g.  Edge, GPRS, had failed more often.

Was the option for that removed? 

And i would like to point out that the loading icon, that cycle is disappearing to fast. The loading isn't even finished.

**Comment by klonamy** [comment]
I looked it up it was with the matherial relese 0.7.0.

**Comment by klonamy** [comment]
It seems one of the reasons is a loading limit set to high, but seldom not.

**Comment by vanita5** [comment]
This behavior has been improved with the last updates. Please reopen if the problem is still present.
