### ISSUE TITLE
Confusing retweet deletion

### ISSUE THREAD

**Issue by Faldrian** [vanita5/twittnuker#71]
Some weeks (months?) ago the retweet was changed so the user can quote a tweet.
When the user taps the retweet-symbol, a dialog is shown to determine if the user wants to retweet or quote.

This change introduced an odd behaviour when deleting a retweet: You click on the retweet-icon and this dialog opens. You have to tap on the  "retweet" button on that dialog to remove the retweet.

I would prefer the retweet button to trigger a simple confirmation ("do you want to delete that retweet?") dialog instead of the retweet-dialog.

**Comment by vanita5** [comment]
There's one problem with your suggestion: What if you want to quote a tweet you already retweeted?

But you're right, it's confusing that it still says "Retweet".

**Comment by Faldrian** [comment]
The issue is not that I don't want this dialog - perfectly fine!
I'm just suggesting to change the dialog that is shown if you want to remove a retweet.

The situation is:
You are on the details screen of a tweet and have already retweetet the tweet. Now you want to remove the retweet again (maybe you retweetet that by mistake).
If you tap the retweet-button (longpress reveals help: "remove retweet" or "delete retweet"), the same "compose quote / retweet" dialog is shown and THAT is the point where I as a user am severly confused, because all I wanted was to delete the retweet and now retweet it again... this dialog just makes no sense.

**Comment by vanita5** [comment]
> If you tap the retweet-button (longpress reveals help: "remove retweet" or "delete retweet"), the same "compose quote / retweet" dialog is shown

That's okay, because maybe you want to quote that tweet, too.
Of course, it's a little inconvenient in this situation to show the same dialog again, but else you wouldn't be able to retweet and quote a tweet without another button for quotes.


> THAT is the point where I as a user am severly confused, because all I wanted was to delete the retweet and not retweet it again... this dialog just makes no sense.

Actually the retweet button should state "Cancel Retweet". This seems to be a bug, give me a second.

**Comment by Faldrian** [comment]
Now that might sound like a partial solution.
From an UX point of view the green lit reshare-button on the tweet states that all actions with this button have been made and (as it was in prior versions) I can undo them by tapping the button again. This pattern was broken with the new dialog. If the "reshare" button of that dialog transforms to a red "cancel retweet" or "undo retweet" (even better that way), this would make more sense. :)

**Comment by vanita5** [comment]
Like this?

![screenshot_2015-11-05-20-14-25](https://cloud.githubusercontent.com/assets/3717962/10978957/fb5a01b2-83f9-11e5-8ae3-337b1ad0891d.png)

**Comment by Faldrian** [comment]
Exactly. Dankesehr! <3
