### ISSUE TITLE
Notification sound is wrong

### ISSUE THREAD

**Issue by IBBoard** [vanita5/twittnuker#75]
Whenever I get a notification of a new @-tweet then the notification it plays is wrong. It sounds like it might be Altair (deep flat "bong"), but I set it Adara (wood blocks).

To recreate:
 * Swipe from Left
 * Tap Settings
 * Tap Notifications
 * Tap my account
 * Tap Ringtone
 * Tap Adara and tap OK
 * Keep clicking "Back" arrow
 * Receive @-notification
 * Hear a ringtone that isn't Adara

Might be https://github.com/TwidereProject/Twidere-Android/issues/187 from upstream

**Comment by vanita5** [comment]
Upstream bug. Fix has been merged.
