### ISSUE TITLE
Feed sometimes jumps to top

### ISSUE THREAD

**Issue by IBBoard** [vanita5/twittnuker#76]
I sometimes get what seems to be the TwittNuker version of [Twidere issue #204](https://github.com/TwidereProject/Twidere-Android/issues/204). It seems to sometimes be random, but the times it happens when I rotate the screen seem to be the times when it has loaded new tweets and decides that I've read everything and need to be put at the top with the new tweets.

**Comment by alerque** [comment]
I've bumped into this (or something like it) a couple times not. I don't have screen rotation enabled though, so that can't be the only trigger. Switching to the TL tab from somewhere else while new tweets had been loaded since I viewed the TL seems to be one trigger (although not consistent).

**Comment by vanita5** [comment]
As this has been reimplemented and theres nothing new since the last updates, I'll close this for now.

Please reopen, if the bug is still present.
