### ISSUE TITLE
Issue: Gif loading with 1 frame

### ISSUE THREAD

**Issue by klonamy** [vanita5/twittnuker#81]
Sometimes when i click on the tweet with a gif, were the preview is loaded, it happens to immediately abort or skip the the loading.

When a gif is animated it loads.
Will try to verify that with my twitter account.

**Comment by klonamy** [comment]
It seems i was wrong it is the png that are both not loading. 

Example Tweets:
- https://mobile.twitter.com/CurryKingWurst/status/686313086958047232

- https://mobile.twitter.com/Pokemon_Days/status/662307138669268992

**Comment by vanita5** [comment]
I just tried to reproduce this with those two tweets. I can't see any problem, everything works as intended...

**Comment by klonamy** [comment]
Can reproduce this, even with faster image loading.

PHone: OnePlus One
OS: CM12.1.1 (Android 5.1.1)

I will attach my config. I didn't found any token or login data inside the zip.
[Twittnuker_Settings_2016-01-17_02-22-31.zip](https://github.com/vanita5/twittnuker/files/93173/Twittnuker_Settings_2016-01-17_02-22-31.zip)

**Comment by vanita5** [comment]
Is this problem still present with the latest update?

**Comment by klonamy** [comment]
No, i came to the conclusion, that it is the ethernetconnection in addition with the number of images loading.
