### ISSUE TITLE
No unread count when scrolling up

### ISSUE THREAD

**Issue by alerque** [vanita5/twittnuker#86]
The red counter above the timeline tab that shows how many tweets have been loaded but not read is not showing up for me in the latest update. It's there for mentions, but nothing for my timeline.

**Comment by schwindp** [comment]
ACKing this. Behaviour changed in 0.8.1.

**Comment by vanita5** [comment]
Is the counter always missing for the TL tab?

**Comment by alerque** [comment]
@vanita5 A counter actually showed on the TL tab the _first_ time I launched after the update. I haven't seen it ever since no matter what sequence of usage I try.

**Comment by alerque** [comment]
This got fixed in one of the next versions released.
