### ISSUE TITLE
Several bugs

### ISSUE THREAD

**Issue by Clouddancer** [vanita5/twittnuker#87]
Hello. Have noticed several bugs in Twittnuker.

- Pictures in DM are not possible to send (Error Message: "Error 37: not authorised to use this endpoint.")
- Tweeted pictures are mostly only opening in thumbnail, not on full screen
- No list of who faved or retweeted your tweet when you go on the "favorites" button under the tweet 
- Muted accounts are still appearing in real live timeline
- After the last update no mention of new arrived DMs
- "Media" doesn't show a pic of a photo/video thumbnail when going on the tab. It's just a grey circle and some lines
- App crashes from time to time when changing something in the settings

**Comment by alerque** [comment]
One issue per issue report please! Otherwise its nearly impossible to track discussions and know what got fixed without missing things. Please open new issues for each items here, but also check for duplicates before you post. I see #59 and #82 for starters.

**Comment by Clouddancer** [comment]
Thanks. I am new to here. Changing it.

**Comment by alerque** [comment]
@Clouddancer Thanks for splitting these up. I'm sorry I didn't note you were new to Github.

So as you're probably seeing, issue trackers are a bit more than just a feedback/reporting interface, they are actually a window into the software development process. Particularly for open source projects like this one good structured issue reports and follow ups are actually part of the development cycle, so you can consider yourself a contributor!

**Comment by Clouddancer** [comment]
You're welcome and thanks for the info.

Thank you very much for explaining the process.
