### ISSUE TITLE
No feedback for "load more" command

### ISSUE THREAD

**Issue by alerque** [vanita5/twittnuker#98]
When breaks in the timeline occur due to having new data loaded that over-ran the API call max, a "LOAD MORE" link is shown. Clicking it makes another request and fills in the gap.

However: no feedback is given to the user on clicking the button that anything is happening. It isn't acknowledged in any way and looks just the same as if it had been ignored until a successful load, which on a bad network can be a long time later or not at all. I find myself clicking it a few times wondering if it's doing anything.

**Comment by gena01** [comment]
There's an interesting point if you scroll from the top down and that triggers loading more tweets then there's a spinner shown until the tweets load. Can the same spinner be shown/triggered on the "Load More" button?

**Comment by alerque** [comment]
I haven't looked at the implementation, but from a UI perspective something like that would work for me.

This problem is even more urgent than when I reported it as my Twitter feed seems to have issue keeping above the API request limit so I'm often stuck hitting the "load more" line and getting nothing back and I have no idea if I hid a rate limiter, have internet connection issues, missed the button, or its  just still working.
